# Numpy -Statistical Operation.

###### Vectorized Operations

In [1]:
import numpy as np

In [2]:
nums = np.arange(6)

In [3]:
#Multiplies each element by 10.

nums * 10


array([ 0, 10, 20, 30, 40, 50])

In [4]:
#Returns square root of each element.

nums = np.sqrt(nums)
nums

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

In [5]:
#Floor, rint (round to nearest int)

np.ceil(nums)

array([0., 1., 2., 2., 2., 3.])

In [6]:
#Checks for NaN

np.isnan(nums) 

array([False, False, False, False, False, False])

In [7]:
#add element-wise

nums  + np.arange(6)

array([0.        , 2.        , 3.41421356, 4.73205081, 6.        ,
       7.23606798])

In [8]:
 #Compare element wise
    
np.maximum(nums,np.array([1,-2,-3,-4,-5,-6])) 

array([1.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798])

###### Maths & Statistical Functions

In [9]:
#Random normals in 4x2 array.

rnd = np.random.randn(4,2)

In [10]:
rnd

array([[ 2.20850817,  0.22528271],
       [ 1.65309786,  0.19360482],
       [ 2.08282011,  1.31058422],
       [ 0.63622042, -0.23288298]])

In [11]:
#Returns mean of  the array.

rnd.mean()

1.0096544155784575

In [12]:
#Return Standard Diviation of the array.

rnd.std()

0.8702040849366142

In [13]:
#Returns the max value of an array.

rnd.max()

2.2085081691713575

In [14]:
#Returns index of max value of an array.

rnd.argmax()

0

In [15]:
#Returns min values of an array.

rnd.min()

-0.23288297882601758

In [16]:
#Returns index of min value of an array.

rnd.argmin()

7

In [17]:
#Returns sum of array.

rnd.sum()

8.07723532462766

In [18]:
#Returns sum of the column
rnd.sum(axis=0)

array([6.58064656, 1.49658876])

In [19]:
#Returns sum of the row
rnd.sum(axis=1)

array([2.43379087, 1.84670268, 3.39340433, 0.40333744])

###### Reshaping the arrays

In [20]:
#Returns a 2-dim, 8 x 4 array.

nums = np.arange(32).reshape(8,4)
nums

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [21]:
#Returns a Transpose of an array

nums.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [22]:
#Returns a 1 dim array.

nums.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

###### Array Creation with Random Numbers

In [23]:
# random 3x3 matrix in [0to1]
np.random.rand(3,3)

array([[0.81868461, 0.00597504, 0.1733761 ],
       [0.39134527, 0.65619674, 0.21765634],
       [0.90695959, 0.09038001, 0.10920431]])

In [24]:
#random normal (mean 0, sd 1)
#randon 3x3 matrix [-1to1]

np.random.randn(3,3)

array([[ 0.37944952,  1.26195917, -1.570232  ],
       [-1.14602986, -1.32666698, -0.13719262],
       [-0.22786722,  1.31030227, -0.47121331]])

In [25]:
#9 randomly picked no. betn 0-4.

np.random.randint(0,5,9)

array([1, 4, 3, 2, 0, 0, 0, 4, 2])

###### Computing Euclidean Distance between 2 vectors.

In [26]:
vec1 = np.random.randn(10)
vec1

array([-0.60794431, -0.35168421, -0.36754283,  1.08702051, -0.8746236 ,
        0.88459329, -1.71310539,  0.16274986, -0.39518672,  2.02351951])

In [27]:
vec2 = np.random.randn(10)
vec2

array([-0.03271702, -1.58363353, -0.11751782, -0.31886654, -1.5344532 ,
       -0.61218808,  2.71713168,  0.04276765, -0.22618237, -1.28455916])

In [28]:
dist = np.sqrt(np.sum(vec1 - vec2)**2)

In [29]:
dist

2.798014517583069