# Numpy - Arithmetics

In [1]:
import numpy as np

In [2]:
A = np.array([[1,5,6],[1,8,9],[0,-1,6]])
B = np.array([[4,8,4],[1,0,5],[6,-8,3]])

In [3]:
A

array([[ 1,  5,  6],
       [ 1,  8,  9],
       [ 0, -1,  6]])

In [4]:
B

array([[ 4,  8,  4],
       [ 1,  0,  5],
       [ 6, -8,  3]])

###### Arithmetical Operations

In [5]:
np.add(A,B)

array([[ 5, 13, 10],
       [ 2,  8, 14],
       [ 6, -9,  9]])

In [6]:
np.subtract(A,B)

array([[-3, -3,  2],
       [ 0,  8,  4],
       [-6,  7,  3]])

In [7]:
np.multiply(A,B)    #pointwise multiplication arr1*arr2

array([[ 4, 40, 24],
       [ 1,  0, 45],
       [ 0,  8, 18]])

In [8]:
np.divide(A,B)

<ipython-input-8-3d3d7deafdeb>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(A,B)


array([[0.25 , 0.625, 1.5  ],
       [1.   ,   inf, 1.8  ],
       [0.   , 0.125, 2.   ]])

In [9]:
np.remainder(A,B)

<ipython-input-9-4ee38155de56>:1: RuntimeWarning: divide by zero encountered in remainder
  np.remainder(A,B)


array([[ 1,  5,  2],
       [ 0,  0,  4],
       [ 0, -1,  0]], dtype=int32)

###### Matrix Product

In [10]:
#dot product or inner product i.e 1st row to 1st col

np.matmul(A,B)

array([[ 45, -40,  47],
       [ 66, -64,  71],
       [ 35, -48,  13]])

In [11]:
#dot product or inner product i.e 1st row to 1st col

np.dot(A,B)

array([[ 45, -40,  47],
       [ 66, -64,  71],
       [ 35, -48,  13]])

In [12]:
#cross product

np.kron(A,B)

array([[  4,   8,   4,  20,  40,  20,  24,  48,  24],
       [  1,   0,   5,   5,   0,  25,   6,   0,  30],
       [  6,  -8,   3,  30, -40,  15,  36, -48,  18],
       [  4,   8,   4,  32,  64,  32,  36,  72,  36],
       [  1,   0,   5,   8,   0,  40,   9,   0,  45],
       [  6,  -8,   3,  48, -64,  24,  54, -72,  27],
       [  0,   0,   0,  -4,  -8,  -4,  24,  48,  24],
       [  0,   0,   0,  -1,   0,  -5,   6,   0,  30],
       [  0,   0,   0,  -6,   8,  -3,  36, -48,  18]])

In [13]:
np.inner(A,B)

array([[ 68,  31, -16],
       [104,  46, -31],
       [ 16,  30,  26]])

In [14]:
np.tensordot(A,B)

array(140)

#### Linear_algebra

In [15]:
#(arr1,2) = arr1 square =dot product

np.linalg.matrix_power(A,2)

array([[  6,  39,  87],
       [  9,  60, 132],
       [ -1, -14,  27]])

###### Cholesky Decomposition   $$U=UU^T$$

In [16]:
# A = A.Atranspose  (some conjugates of transpose)

np.linalg.cholesky(A)

array([[ 1.        ,  0.        ,  0.        ],
       [ 1.        ,  2.64575131,  0.        ],
       [ 0.        , -0.37796447,  2.42015348]])

###### Q R Decomposition      $$A=QR$$
,where Q is orthogonal matrix , R is Upper trinagular

In [17]:
#for upper triangular A= Q.R

np.linalg.qr(A)[1]

array([[ -1.41421356,  -9.19238816, -10.60660172],
       [  0.        ,  -2.34520788,   0.63960215],
       [  0.        ,   0.        ,   6.33173824]])

In [18]:
#for Q

np.linalg.qr(A)[0]

array([[-0.70710678,  0.63960215, -0.30151134],
       [-0.70710678, -0.63960215,  0.30151134],
       [-0.        ,  0.42640143,  0.90453403]])

In [19]:
#for extracting the diagonal elements

np.diag(A)

array([1, 8, 6])

###### Eigen Value Decomposition       $$A=PDP^{-1}$$

In [20]:
#for eigen value decomposition A= PDP-1

(d,P)=np.linalg.eig(A)

In [21]:
d

array([0.34454138+0.j        , 7.32772931+2.69350537j,
       7.32772931-2.69350537j])

In [22]:
P

array([[ 0.9940235 +0.j        ,  0.52656174+0.00429702j,
         0.52656174-0.00429702j],
       [-0.10749871+0.j        ,  0.80658014+0.j        ,
         0.80658014-0.j        ],
       [-0.01900796+0.j        , -0.11875577+0.24091455j,
        -0.11875577-0.24091455j]])

In [23]:
D =np.diag(d)

In [24]:
D

array([[0.34454138+0.j        , 0.        +0.j        ,
        0.        +0.j        ],
       [0.        +0.j        , 7.32772931+2.69350537j,
        0.        +0.j        ],
       [0.        +0.j        , 0.        +0.j        ,
        7.32772931-2.69350537j]])

In [25]:
np.real(np.matmul(np.matmul(P,D),np.linalg.inv(P)))

array([[ 1.00000000e+00,  5.00000000e+00,  6.00000000e+00],
       [ 1.00000000e+00,  8.00000000e+00,  9.00000000e+00],
       [-5.55111512e-17, -1.00000000e+00,  6.00000000e+00]])

In [26]:
np.linalg.eigvals(A)

array([0.34454138+0.j        , 7.32772931+2.69350537j,
       7.32772931-2.69350537j])

###### Singluar Valued Decomposition    $$A=USV^T$$

In [27]:
#for singular valued decomposition A=USVtranspose

(U,s,V) = np.linalg.svd(A)

In [28]:
U

array([[ 0.52419682, -0.12063215,  0.84300983],
       [ 0.80286468, -0.26006138, -0.53644792],
       [ 0.28394717,  0.95802712, -0.03947205]])

In [29]:
s

array([14.9764806 ,  4.53978289,  0.30886909])

In [30]:
V

array([[ 0.0886097 ,  0.58491408,  0.80624056],
       [-0.08385721, -0.80217028,  0.59117747],
       [ 0.99253025, -0.11999315, -0.02203081]])

###### Matrix  & Determinants

In [31]:
#for determinant of the matrix

np.linalg.det(A) 

21.0

In [32]:
# for rank of the matrix

np.linalg.matrix_rank(A)

3

In [33]:
#trace is the sum of diagonal element

np.trace(A)

15

In [34]:
#Give the diagonal elements of the matrix

np.diag(A)

array([1, 8, 6])

###### Matrix Norms

In [35]:
np.linalg.norm(A)

15.652475842498529

In [36]:
#conditional number which tells you how close you are to singularity
np.linalg.cond(A)

48.48811774406207

In [37]:
np.linalg.cond(B)

3.6136804102640414

###### Solving linear Equations

In [38]:
#for solving linear equations A.x = b -> x=A-1.b

np.linalg.solve(A,B)

array([[ 8.28571429, 22.85714286,  1.85714286],
       [-1.71428571, -1.14285714, -0.14285714],
       [ 0.71428571, -1.52380952,  0.47619048]])

In [39]:
# 2nd way of solving equations

x = np.matmul(np.linalg.inv(A),B)   

In [40]:
x

array([[ 8.28571429, 22.85714286,  1.85714286],
       [-1.71428571, -1.14285714, -0.14285714],
       [ 0.71428571, -1.52380952,  0.47619048]])

In [41]:
# singular matrix is a non invertible matrix for that 
#we can use psuedo inverse

np.linalg.pinv(A)

array([[ 2.71428571, -1.71428571, -0.14285714],
       [-0.28571429,  0.28571429, -0.14285714],
       [-0.04761905,  0.04761905,  0.14285714]])

# Trigonometric Functions

In [42]:
#Numpy Trigonometric functions
print('sin =>',np.sin(90))
print('cos =>',np.cos(90))
print('log =>',np.log(10))
print('log =>',np.log(1))
print('log10 =>',np.log10(10))
print(np.log(np.log10(5)))

sin => 0.8939966636005579
cos => -0.4480736161291701
log => 2.302585092994046
log => 0.0
log10 => 1.0
-0.35814744992084513
